services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oneshotmanga
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - OLLAMA_HOST=ollama
    depends_on:
      - mysql
      - redis
      - ollama
    networks:
      - app-network
  mysql:
    image: mysql:8.0.41-debian
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  redis:
    image: redis:bookworm
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    entrypoint: /bin/sh
    command: -c "
      ollama serve & 
      sleep 3 && 
      ollama list | grep -q 'mistral' || ollama pull mistral && 
      wait 
      "

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  ollama_data:
    driver: local